- menu_name: "Info"

- name: "Impressum"
  url: "/pages/impressum/"
  title: "Impressum"

- name: "Datenschutz"
  url: "/pages/datenschutz/"
  title: "Datenschutz"

- name: "RSS"
  url: "/feed.xml"
  title: "RSS feed abonnieren"
